Fix build errors in wifi_wpa_supplicant with MDK
[Description]
Below build errors were found when compiling wifi_wpa_supplicant with
MDK:
1. mcuxsdk/middleware/wireless/wpa_supplicant-rtos/port/mbedtls/supp_crypto.c:65:5: error:
conflicting types for '_gettimeofday'
2. Error: L6218E: Undefined symbol time (referred from platform.o).
Not enough information to list image symbols.

[Root Cause]
1. Not include header file that defines the structure timeval.
2. No time function implemented in SDK

[Fix]
1. Include header file for timeval.
2. Implemented time function in supp_crypto.c

[Testing]
Compilation is ok.

[Reviewers]
Gannicus Guo, Rex Chen

Change-Id: I2544e2eb5c90c52133483d42cfcf8f80eba30804
Signed-off-by: Hui Bai <hui.bai@nxp.com>